services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    env_file: .env
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped
